// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
Compressor* RobotMap::pressurizerCompressor = NULL;
DoubleSolenoid* RobotMap::shifterShifter = NULL;
CANJaguar* RobotMap::shooterShooter1 = NULL;
CANJaguar* RobotMap::shooterShooter2 = NULL;
Encoder* RobotMap::shooterShooEncoder = NULL;
CANJaguar* RobotMap::chassisFrontLeft = NULL;
CANJaguar* RobotMap::chassisRearLeft = NULL;
CANJaguar* RobotMap::chassisFrontRight = NULL;
CANJaguar* RobotMap::chassisRearRight = NULL;
RobotDrive* RobotMap::chassisRobotDrive = NULL;
Encoder* RobotMap::chassisLEncoder = NULL;
Encoder* RobotMap::chassisREncoder = NULL;
CANJaguar* RobotMap::armArm1 = NULL;
CANJaguar* RobotMap::armArm2 = NULL;
AnalogChannel* RobotMap::armPotentiometer = NULL;
DoubleSolenoid* RobotMap::intakeSpoiler = NULL;
CANJaguar* RobotMap::intakeIntake = NULL;
DoubleSolenoid* RobotMap::conveyorStopper = NULL;
CANJaguar* RobotMap::conveyorConveyor = NULL;
Relay* RobotMap::lightsLights = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	pressurizerCompressor = new Compressor(1, 1, 1, 3);
	
	
	shifterShifter = new DoubleSolenoid(1, 4, 8);      
	
	
	shooterShooter1 = new CANJaguar(7);
	
	
	shooterShooter2 = new CANJaguar(12);
	
	
	shooterShooEncoder = new Encoder(1, 6, 1, 7, false, Encoder::k4X);
	lw->AddSensor("Shooter", "ShooEncoder", shooterShooEncoder);
	shooterShooEncoder->SetDistancePerPulse(1.0);
        shooterShooEncoder->SetPIDSourceParameter(Encoder::kRate);
        shooterShooEncoder->Start();
	chassisFrontLeft = new CANJaguar(2);
	
	
	chassisRearLeft = new CANJaguar(3);
	
	
	chassisFrontRight = new CANJaguar(4);
	
	
	chassisRearRight = new CANJaguar(5);
	
	
	chassisRobotDrive = new RobotDrive(chassisFrontLeft, chassisRearLeft,
              chassisFrontRight, chassisRearRight);
	
	chassisRobotDrive->SetSafetyEnabled(true);
        chassisRobotDrive->SetExpiration(0.1);
        chassisRobotDrive->SetSensitivity(0.5);
        chassisRobotDrive->SetMaxOutput(1.0);
	chassisLEncoder = new Encoder(1, 2, 1, 3, false, Encoder::k4X);
	lw->AddSensor("Chassis", "LEncoder", chassisLEncoder);
	chassisLEncoder->SetDistancePerPulse(1.0);
        chassisLEncoder->SetPIDSourceParameter(Encoder::kDistance);
        chassisLEncoder->Start();
	chassisREncoder = new Encoder(1, 4, 1, 5, false, Encoder::k4X);
	lw->AddSensor("Chassis", "REncoder", chassisREncoder);
	chassisREncoder->SetDistancePerPulse(1.0);
        chassisREncoder->SetPIDSourceParameter(Encoder::kDistance);
        chassisREncoder->Start();
	armArm1 = new CANJaguar(11);
	
	
	armArm2 = new CANJaguar(10);
	
	
	armPotentiometer = new AnalogChannel(1, 1);
	lw->AddSensor("Arm", "Potentiometer", armPotentiometer);
	
	intakeSpoiler = new DoubleSolenoid(1, 7, 3);      
	
	
	intakeIntake = new CANJaguar(8);
	
	
	conveyorStopper = new DoubleSolenoid(1, 2, 6);      
	
	
	conveyorConveyor = new CANJaguar(9);
	
	
	lightsLights = new Relay(1, 2);
	lw->AddActuator("Lights", "Lights", lightsLights);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
