// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static Compressor* pressurizerCompressor;
	static DoubleSolenoid* shifterShifter;
	static CANJaguar* shooterShooter1;
	static CANJaguar* shooterShooter2;
	static Encoder* shooterShooEncoder;
	static CANJaguar* chassisFrontLeft;
	static CANJaguar* chassisRearLeft;
	static CANJaguar* chassisFrontRight;
	static CANJaguar* chassisRearRight;
	static RobotDrive* chassisRobotDrive;
	static Encoder* chassisLEncoder;
	static Encoder* chassisREncoder;
	static CANJaguar* armArm1;
	static CANJaguar* armArm2;
	static AnalogChannel* armPotentiometer;
	static DoubleSolenoid* intakeSpoiler;
	static CANJaguar* intakeIntake;
	static DoubleSolenoid* conveyorStopper;
	static CANJaguar* conveyorConveyor;
	static Relay* lightsLights;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
