// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef AUTOMATICSHIFTERS_H
#define AUTOMATICSHIFTERS_H


#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author aaronistheman
 */
class AutomaticShifters: public Command {
public:
	AutomaticShifters();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
	
	double GetSlope() const
	{ return slope; }
	
	double GetCurrent() const
	{ return prevCurrent; }
	
	
private:	
	static const double k10ms = .010;
	double slope; //holds slope of current over time 
		          //to decide when to shift
	double Sol; //solenoid value
	double shiftCount;
	double prevCurrent; //hold current sample
	
	static void gGetCurrentSlope(void* param);
	void calcCurrentSlope();
	
	Notifier currentSampler;
};

#endif
